/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  displayName: 'cli',
  preset: 'ts-jest',
  testEnvironment: 'node',
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      { tsconfig: '<rootDir>/tsconfig.spec.json', diagnostics: false },
    ],
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  testMatch: ['<rootDir>/src/**/*.spec.ts'],
  moduleNameMapper: {
    '^shared-kernel$': '<rootDir>/../../libs/shared/kernel/src/index.ts',
    '^shared-kernel/(.*)$': '<rootDir>/../../libs/shared/kernel/src/$1',
    '^cloud-cost-domain$': '<rootDir>/../../libs/cloud-cost/domain/src/index.ts',
    '^cloud-cost-domain/(.*)$': '<rootDir>/../../libs/cloud-cost/domain/src/$1',
    '^cloud-cost-application$': '<rootDir>/../../libs/cloud-cost/application/src/index.ts',
    '^cloud-cost-application/(.*)$': '<rootDir>/../../libs/cloud-cost/application/src/$1',
    '^cloud-cost-infrastructure-aws-adapter$': '<rootDir>/../../libs/cloud-cost/infrastructure/aws-adapter/src/index.ts',
    '^cloud-cost-infrastructure-aws-adapter/(.*)$': '<rootDir>/../../libs/cloud-cost/infrastructure/aws-adapter/src/$1',
    '^cost-analytics-domain$': '<rootDir>/../../libs/cost-analytics/domain/src/index.ts',
    '^cost-analytics-domain/(.*)$': '<rootDir>/../../libs/cost-analytics/domain/src/$1',
    '^cost-analytics-application$': '<rootDir>/../../libs/cost-analytics/application/src/index.ts',
    '^cost-analytics-application/(.*)$': '<rootDir>/../../libs/cost-analytics/application/src/$1',
    '^cost-analytics-infrastructure-aws-adapter$': '<rootDir>/../../libs/cost-analytics/infrastructure/aws-adapter/src/index.ts',
    '^cost-analytics-infrastructure-aws-adapter/(.*)$': '<rootDir>/../../libs/cost-analytics/infrastructure/aws-adapter/src/$1',
    '^dead-resources-domain$': '<rootDir>/../../libs/dead-resources/domain/src/index.ts',
    '^dead-resources-domain/(.*)$': '<rootDir>/../../libs/dead-resources/domain/src/$1',
    '^dead-resources-application$': '<rootDir>/../../libs/dead-resources/application/src/index.ts',
    '^dead-resources-application/(.*)$': '<rootDir>/../../libs/dead-resources/application/src/$1',
    '^dead-resources-infrastructure-aws-adapter$': '<rootDir>/../../libs/dead-resources/infrastructure/aws-adapter/src/index.ts',
    '^dead-resources-infrastructure-aws-adapter/(.*)$': '<rootDir>/../../libs/dead-resources/infrastructure/aws-adapter/src/$1',
    '^resource-security-domain$': '<rootDir>/../../libs/resource-security/domain/src/index.ts',
    '^resource-security-domain/(.*)$': '<rootDir>/../../libs/resource-security/domain/src/$1',
    '^resource-security-application$': '<rootDir>/../../libs/resource-security/application/src/index.ts',
    '^resource-security-application/(.*)$': '<rootDir>/../../libs/resource-security/application/src/$1',
    '^resource-security-infrastructure-aws-adapter$': '<rootDir>/../../libs/resource-security/infrastructure/aws-adapter/src/index.ts',
    '^resource-security-infrastructure-aws-adapter/(.*)$': '<rootDir>/../../libs/resource-security/infrastructure/aws-adapter/src/$1',
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
};
