// SPDX-License-Identifier: Apache-2.0

/**
 * Read-only IAM actions cloudrift needs to run every domain (cloud-cost,
 * dead-resources, resource-security, cost-trend). Kept in sync by hand with
 * `docs/en/iam-permissions.md`. Shared by the `iam-policy` CLI command and
 * the `get_required_iam_permissions` MCP tool, which both expose the exact
 * same union policy.
 */
export const REQUIRED_IAM_POLICY = {
  Version: '2012-10-17',
  Statement: [
    {
      Effect: 'Allow',
      Action: [
        'ec2:DescribeVolumes',
        'ec2:DescribeAddresses',
        'ec2:DescribeInstances',
        'ec2:DescribeSnapshots',
        'ec2:DescribeImages',
        'ec2:DescribeNatGateways',
        'ec2:DescribeNetworkInterfaces',
        'ec2:DescribeLaunchTemplates',
        'ec2:DescribeLaunchTemplateVersions',
        'ec2:DescribeKeyPairs',
        'ec2:DescribeReservedInstances',
        'ec2:DescribeSecurityGroups',
        'ec2:DescribeRegions',
        'ec2:DescribeSnapshotAttribute',
        'cloudwatch:GetMetricStatistics',
        'cloudwatch:DescribeAlarms',
        'rds:DescribeDBInstances',
        'rds:DescribeDBClusters',
        'rds:DescribeDBSnapshots',
        'elasticloadbalancing:DescribeLoadBalancers',
        'elasticloadbalancing:DescribeTargetGroups',
        'elasticloadbalancing:DescribeTargetHealth',
        'logs:DescribeLogGroups',
        's3:ListAllMyBuckets',
        's3:ListBucket',
        's3:GetBucketLifecycleConfiguration',
        's3:ListMultipartUploadParts',
        's3:ListBucketMultipartUploads',
        's3:GetBucketAcl',
        's3:GetBucketPolicyStatus',
        's3:GetPublicAccessBlock',
        's3:GetBucketEncryption',
        'ecr:DescribeRepositories',
        'ecr:DescribeImages',
        'codepipeline:ListPipelines',
        'codepipeline:ListPipelineExecutions',
        'secretsmanager:ListSecrets',
        'lambda:ListFunctions',
        'elasticfilesystem:DescribeFileSystems',
        'dynamodb:ListTables',
        'dynamodb:DescribeTable',
        'elasticache:DescribeCacheClusters',
        'sagemaker:ListNotebookInstances',
        'sagemaker:ListEndpoints',
        'sagemaker:DescribeEndpoint',
        'sagemaker:DescribeEndpointConfig',
        'sagemaker:ListEndpointConfigs',
        'sagemaker:ListModels',
        'sagemaker:DescribeModel',
        'sagemaker:ListTags',
        'sqs:ListQueues',
        'sqs:GetQueueAttributes',
        'sqs:ListDeadLetterSourceQueues',
        'sqs:ListQueueTags',
        'tag:GetResources',
        'eks:ListClusters',
        'eks:ListNodegroups',
        'eks:DescribeNodegroup',
        'iam:ListUsers',
        'iam:ListAccessKeys',
        'iam:GetAccessKeyLastUsed',
        'iam:ListPolicies',
        'iam:ListRoles',
        'iam:ListInstanceProfiles',
        'iam:GetAccountSummary',
        'iam:ListMFADevices',
        'iam:GetAccountPasswordPolicy',
        'acm:ListCertificates',
        'route53:ListHostedZones',
        'cloudformation:DescribeStacks',
        'sns:ListTopics',
        'sns:ListSubscriptionsByTopic',
        'events:ListRules',
        'events:ListTargetsByRule',
        'states:ListStateMachines',
        'states:ListExecutions',
        'cloudtrail:DescribeTrails',
        'ce:GetCostAndUsage',
        'sts:GetCallerIdentity',
        // resource-security v2 (2026-07-31)
        'guardduty:ListDetectors',
        'config:DescribeConfigurationRecorderStatus',
        'securityhub:DescribeHub',
        'ec2:DescribeVpcs',
        'ec2:DescribeFlowLogs',
        'kms:ListKeys',
        'kms:DescribeKey',
        'kms:GetKeyRotationStatus',
        's3:GetAccountPublicAccessBlock',
        's3:GetBucketVersioning',
        'redshift:DescribeClusters',
        'iam:ListAttachedUserPolicies',
        'iam:GetPolicy',
        'iam:GetPolicyVersion',
        'iam:ListUserPolicies',
        'iam:GetUserPolicy',
        'acm:DescribeCertificate',
        'lambda:GetPolicy',
        'sns:GetTopicAttributes',
        'ecr:GetRepositoryPolicy',
        'secretsmanager:GetResourcePolicy',
        // Only needed when scanning with --assume-role-arn: this grants the
        // CALLING principal permission to assume a role elsewhere. The
        // TARGET role (in the account being scanned) needs its own trust
        // policy granting this principal — that trust relationship isn't
        // expressible here, see docs/en/iam-permissions.md for a sample.
        'sts:AssumeRole',
      ],
      Resource: '*',
    },
  ],
} as const;
