// SPDX-License-Identifier: Apache-2.0

/** One terminal character's worth of a sampled image, half-block encoded (top pixel = foreground, bottom pixel = background). Shared shape for the icon and the title wordmark — both generated by scripts/generate-brand-mark-*.mjs and rendered the same way in brand-mark.ts. */
export interface PixelArtCell {
  /** Hex color of the cell's top source pixel, or null if transparent. */
  top: string | null;
  /** Hex color of the cell's bottom source pixel, or null if transparent. */
  bottom: string | null;
}
